# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-12 16:25
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='scoreboard',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(blank=True, max_length=123, null=True)),
                ('tourProblem', models.CharField(blank=True, max_length=9999, null=True)),
                ('userSolution', models.CharField(blank=True, max_length=999, null=True)),
                ('userLength', models.CharField(blank=True, max_length=9999, null=True)),
                ('algorithmName', models.CharField(blank=True, max_length=9999, null=True)),
                ('algorithmLength', models.CharField(blank=True, max_length=9999, null=True)),
                ('dateSubmitted', models.DateField(default=datetime.date.today)),
                ('numberOfNodes', models.CharField(blank=True, max_length=9999, null=True)),
            ],
        ),
    ]
